version: '3.4'
services:
  db:
    hostname: mysql
    platform: linux/arm64
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product
    ports:
      - "3306:3306"

volumes:
  db_data:
